service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:450515178543:table/MoviesTable 

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get 
  createMovie:        
    handler: src/addMovie.addMovie
    events: 
      - httpApi:
          path: /movies
          method: post 
  getMovies:
    handler: src/getMovies.getMovies
    events:
      - httpApi:
          path: /movies
          method: get
  updateMovie:
    handler: src/updateMovie.updateMovie
    events:
      - httpApi:
          path: /movies/{id}
          method: put
  deleteMovie:
    handler: src/deleteMovie.deleteMovie
    events:
      - httpApi:
          path: /movies/{id}
          method: delete                  

resources:
  Resources:
    MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MoviesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"